### ISSUE TITLE
Make a new release (and keep making them)

### ISSUE THREAD

**Issue by kjk** [microsoft/go-winio#154]
Last release was on Feb 21 and there's been a lot of work since then.

Unfortunately, the behavior of go too,l when used with modules, is that it considers latest release as the latest version so people using `go-winio` are getting a pretty old version.

Please make a new release (and keep making them with some regularity).

**Comment by jterry75** [comment]
https://github.com/microsoft/go-winio/releases/tag/v0.4.13

**Comment by jterry75** [comment]
Hope this helps!

**Comment by kjk** [comment]
Thanks, I appreciate it!
