### ISSUE TITLE
New release of go-winio to support the new pkg/process

### ISSUE THREAD

**Issue by dims** [microsoft/go-winio#167]
pkg/process that was introduced in https://github.com/microsoft/go-winio/commit/f272bf30b3688d687e78f81da3e1d8caa2dba212 and is being used already in:
https://github.com/microsoft/hcsshim/commit/1e4afe9fdf8f3210e7631d1f21ae3c40d5ad87ae#diff-557d18187d922c13ba3a0277fac10fa3R9

Can we please cut a release to support the new code and then update microsoft/hcsshim?

Context - trying to rationalize the dependencies and bring in newer versions of stuff into kubernetes ( WIP in https://github.com/kubernetes/kubernetes/pull/86975 )

**Comment by TBBle** [comment]
https://github.com/microsoft/go-winio/releases/tag/v0.4.15 appears to have taken care of this.

**Comment by dims** [comment]
thanks @TBBle !
