### ISSUE TITLE
Test case fails because of localized account names

### ISSUE THREAD

**Issue by bitgestalt** [microsoft/go-winio#202]
[TestLookupValidSid](https://github.com/microsoft/go-winio/blob/5516f17a595844b6011597b41d9573aafabb6b6a/sd_test.go#L16) tries to lookup the SID for the group "Everyone". Since Windows uses localized names for built-in accounts, this test case will fail when executed under non-English versions of Windows.

**Comment by yusufpapurcu** [comment]
No it does not fail in Turkish Windows 10 Home. I don't know exactly why but I think function localize group name in api side.

**Comment by bitgestalt** [comment]
> No it does not fail in Turkish Windows 10 Home. I don't know exactly why but I think function localize group name in api side.

I think not every localized version of Windows uses translated account names. If the group with SID "S-1-1-0" is named "Everyone", the test will work, otherwise it won't. On my German system for example, the account is named "Jeder" which is why the test fails.
