### ISSUE TITLE
Release of go-winio for go1.22 support

### ISSUE THREAD

**Issue by winkingturtle-vmw** [microsoft/go-winio#316]
Thanks @dagood for adding support for go1.22 in [this pr](https://github.com/microsoft/go-winio/pull/312). We currently [pull the latest released](https://github.com/cloudfoundry/groot-windows/blob/main/go.mod#L12) version of this library and since the last release of this library was about a year ago, we are unable to pull the latest changes. It looks like [moby will be running](https://github.com/moby/moby/pull/46982/files#diff-3cf15fd4671254ae18dff1505434826e26a59cdc6e0d945dd4da1e0d63819602R17) into the same issue. Would it be possible to cut a new release of this library so that we can complete our migration to go1.22?

**Comment by dagood** [comment]
It looks like this has been done as of 3 days ago: https://github.com/microsoft/go-winio/releases/tag/v0.6.2 🎉 

(Sorry for the delayed response, was busy last week. I don't have tagging power, but I could have potentially looped someone in.)

**Comment by winkingturtle-vmw** [comment]
Thank you for releasing go-winio, we are now able to move forward with our upgrade plan.
