### ISSUE TITLE
Possible race 

### ISSUE THREAD

**Issue by jhowardmsft** [Microsoft/go-winio#32]
Found running CI on a daemon instrumented with go race detector.  @jstarks 
# 

WARNING: DATA RACE
Write at 0x00c042296dd8 by goroutine 14:
  github.com/Microsoft/go-winio.(_win32File).closeHandle()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:92 +0x7b
  github.com/Microsoft/go-winio.(_win32File).Close()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:103 +0x55
  github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:275 +0x47c

Previous read at 0x00c042296dd8 by goroutine 94:
  github.com/Microsoft/go-winio.(_win32File).asyncIo()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:145 +0x167
  github.com/Microsoft/go-winio.connectPipe()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:360 +0x1b0
  github.com/Microsoft/go-winio.(_win32PipeListener).listenerRoutine.func1()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:265 +0x56

Goroutine 14 (running) created at:
  github.com/Microsoft/go-winio.ListenPipe()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:350 +0x6ce
  github.com/docker/docker/pkg/listeners.Init()
      e:/go/src/github.com/docker/docker/pkg/listeners/listeners_windows.go:43 +0x8e1
  main.(_DaemonCli).start()
      e:/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:215 +0x1f80
  main.runDaemon()
      e:/go/src/github.com/docker/docker/cmd/dockerd/docker.go:75 +0x25a
  main.newDaemonCommand.func1()
      e:/go/src/github.com/docker/docker/cmd/dockerd/docker.go:41 +0xe9
  github.com/spf13/cobra.(_Command).execute()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:643 +0xa03
  github.com/spf13/cobra.(_Command).ExecuteC()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:739 +0x7ba
  github.com/spf13/cobra.(_Command).Execute()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:692 +0x51
  main.main()
      e:/go/src/github.com/docker/docker/cmd/dockerd/docker.go:99 +0x152

Goroutine 94 (running) created at:
  github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine()
      e:/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:266 +0x305

```
```

**Comment by samuelkarp** [comment]
@jhowardmsft @jstarks I opened https://github.com/Microsoft/go-winio/pull/31 to fix this.

**Comment by darrenstahlmsft** [comment]
This was fixed by https://github.com/Microsoft/go-winio/pull/59/files
