### ISSUE TITLE
Re-evaluate "cgo" dependency?

### ISSUE THREAD

**Issue by danjacques** [Microsoft/go-winio#49]
As of [23ad5a714ce953959ea79723df23a913ff886ddd](https://github.com/Microsoft/go-winio/commit/23ad5a714ce953959ea79723df23a913ff886ddd), the `go-winio` package depends on `cgo`. Some projects, mine included, try to avoid `cgo` dependencies because of the can of worms it opens, including adding complexity to cross-compiling and, in my case, the addition of the `gcc` toolchain to builder systems.

If `cgo` is required, so be it, but I figured I'd at least raise the issue for discussion. Is there any way to achieve a similar end without it? Thanks!

**Comment by darrenstahlmsft** [comment]
Worked on the fix before noticing this issue. Looks removable.

**Comment by ofiliz** [comment]
The Azure/azure-container-networking repo has a dependency on go-winio through hcsshim. It looks like the cgo dependency broke the Windows cross-compilation on Linux build machines. +1 for @danjacques ' comment on build complexity.

@darrenstahlmsft I tried your fix and it solved my build problems. Thank you!

**Comment by danjacques** [comment]
Awesome, thanks much for resolving this so quickly!
