### ISSUE TITLE
Windows Kubelet crashes with the below stacktrace

### ISSUE THREAD

**Issue by madhanrm** [Microsoft/go-winio#57]
goroutine 26 [running]:
runtime.throw(0x33d1a16, 0x2a)
        /home/madhanm/go/src/runtime/panic.go:596 +0x9c fp=0xc042425e08 sp=0xc042425de8
runtime.sigpanic()
        /home/madhanm/go/src/runtime/signal_windows.go:155 +0x18b fp=0xc042425e38 sp=0xc042425e08
runtime.lock(0xc05)
        /home/madhanm/go/src/runtime/lock_sema.go:43 +0x65 fp=0xc042425e70 sp=0xc042425e38
runtime.chansend(0x2c24f20, 0xbad, 0xc042425fb0, 0xc042425f01, 0x27e4daa, 0xc042425f9c)
        /home/madhanm/go/src/runtime/chan.go:176 +0xba fp=0xc042425f20 sp=0xc042425e70
runtime.chansend1(0x2c24f20, 0xbad, 0xc042425fb0)
        /home/madhanm/go/src/runtime/chan.go:113 +0x4d fp=0xc042425f60 sp=0xc042425f20
k8s.io/kubernetes/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x304)
        /home/madhanm/repo/gopath/src/k8s.io/k8swin166/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Microsoft/go-winio/file.go:131 +0xea fp=0xc042425fd8 sp=0xc042425f60
runtime.goexit()
        /home/madhanm/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc042425fe0 sp=0xc042425fd8
created by k8s.io/kubernetes/vendor/github.com/Microsoft/go-winio.initIo
        /home/madhanm/repo/gopath/src/k8s.io/k8swin166/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Microsoft/go-winio/file.go:55 +0x87

**Comment by darrenstahlmsft** [comment]
Already resolved this via email, but for others seeing this thread; this issue was fixed by https://github.com/Microsoft/go-winio/pull/48
